

site_name: Armbian Documentation

repo_url: https://github.com/lanefu/armbianDocsAndProcess
repo_name: Github

site_author: "Armbian team"
google_analytics: ['UA-284946-9', 'docs.armbian.com']

theme: readthedocs
theme_dir: readthedocs_custom

markdown_extensions:
  - smarty
  - footnotes
  - toc:
      permalink: True

pages:
  - Home: index.md
  - 'User Guide' :
        - 'Getting Started' : 'User-Guide_Getting-Started.md'
        - 'Advanced Features' : 'User-Guide_Advanced-Features.md'
        - 'Fine Tuning' : 'User-Guide_Fine-Tuning.md'
        - 'Allwinner DT overlays' : 'User-Guide_Allwinner_overlays.md'

  - 'Hardware Notes' :
        - 'Allwinner (Generic)' : 'Hardware_Allwinner.md'
        - 'A10 and A20' : 'Hardware_Allwinner-A20.md'
        - 'H2+ and H3' : 'Hardware_Allwinner-H3.md'
        - 'H5 and A64' : 'Hardware_Allwinner-H5-A64.md'
        - 'Freescale i.MX6' : 'Hardware_Freescale-imx6.md'
        - 'Marvell Armada' : 'Hardware_Marvell.md'

  - 'Developer Guide' :
        - 'Building Armbian' : 'Developer-Guide_Build-Preparation.md'
        - 'Build Options' : 'Developer-Guide_Build-Options.md'
        - 'User Configurations' : 'Developer-Guide_User-Configurations.md'
        - 'Build Process Explained' : 'Developer-Guide_Build-Process.md'
        - 'FEL boot' : 'Developer-Guide_FEL-boot.md'

  - 'Contributor Process' :
        - 'Contribute' : 'Process_Contribute.md'
        - 'Armbian Task Tracking' : 'Process_Armbian-Task-Tracking.md'
        - 'Documentation' : 'Process_Documentation.md'

  - 'Release' :
        - 'Download' : 'Release_Download.md'
        - 'Changelog' : 'Release_Changelog.md'

